global:
  resolve_timeout: 10m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: ''
  wechat_api_corp_id: ''
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_hello: 'qq.com'
  smtp_require_tls: false
templates:
#  - '/var/gnway/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 360m
  receiver: gnway
receivers:
- name: gnway
  webhook_configs:
  - url: http:/dingtalk/dingding/send
    send_resolved: true
  email_configs:
  - to: ''
    send_resolved: true
   # html: '{{ template "wps.html" . }}'
  #  headers: { Subject: " {{ .CommonAnnotations.summary }}" }
  wechat_configs:
  - send_resolved: true
    to_party: '1'
    agent_id: '1000003'
    api_url: ''
    api_secret: ''
    corp_id: '
